version: "3.3"

services:
  message-broker:
    image: rabbitmq:3-management-alpine
    container_name: message-broker
    ports:
      - 5672:5672 # for sender and consumer connections
      - 15672:15672 # for serve RabbitMQ GUI
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    labels:
      reproxy.port: 15672

  zima:
    build: .
    container_name: zima
    ports:
      - ${PORT}:${PORT}
    expose:
      - ${PORT}
    volumes:
      - ${VPN_FILES_PATH}:/usr/src/vpns
    environment:
      PORT: ${PORT}
      AMQP_SERVER_URL: ${AMQP_SERVER_URL}
      AMQP_ANSIBLE_QUEUE_NAME: ${AMQP_ANSIBLE_QUEUE_NAME}
      AMQP_MEETINGS_QUEUE_NAME: ${AMQP_MEETINGS_QUEUE_NAME}
      AMQP_SMART_DEVICES_QUEUE_NAME: ${AMQP_SMART_DEVICES_QUEUE_NAME}
      AMQP_SPOTIFY_QUEUE_NAME: ${AMQP_SPOTIFY_QUEUE_NAME}
      VPN_FILES_PATH: "/usr/src/vpns"
    restart: unless-stopped
    depends_on:
      - message-broker
    labels:
      reproxy.server: '*'
      reproxy.route: '^/(.*)'
      reproxy.dest: '/$$1'

  meetings-service:
    build:
      context: ./microservices/meeting-service
      dockerfile: Dockerfile
    container_name: meetings-service
    volumes:
      - ./microservices/meeting-service/credentials.json:/app/credentials.json
      - ./microservices/meeting-service/token.json:/app/token.json
    environment:
      AMQP_MEETINGS_QUEUE_NAME: ${AMQP_MEETINGS_QUEUE_NAME}
      AMQP_SERVER_URL: ${AMQP_SERVER_URL}
    restart: unless-stopped
    depends_on:
      - message-broker
    labels:
      reproxy.enabled: 0

  spotify-service:
    build:
      context: .
      dockerfile: microservices/spotify-service/Dockerfile
    container_name: spotify-service
    hostname: spotify-service
    volumes:
      - ./microservices/spotify-service/auth.json:/app/auth.json
    environment:
      AMQP_SERVER_URL: ${AMQP_SERVER_URL}
      AMQP_SPOTIFY_QUEUE_NAME: ${AMQP_SPOTIFY_QUEUE_NAME}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      SPOTIFY_REDIRECT_URI: ${SPOTIFY_REDIRECT_URI}
    restart: unless-stopped
    depends_on:
      - message-broker
    expose:
      - 3000

  reproxy:
    image: umputun/reproxy:master
    container_name: zima-api
    hostname: reproxy
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Europe/Warsaw
      - LISTEN=0.0.0.0:8080
      - DOCKER_ENABLED=true
      - DOCKER_AUTO=true
      - DEBUG=true
      - TIMEOUT_RESP_HEADER=640s
      - TIMEOUT_WRITE=640s
      - TIMEOUT_IDLE=640s
      - TIMEOUT_DIAL=640s
      - TIMEOUT_KEEP_ALIVE=640s
      - MAX_SIZE=0
    restart: unless-stopped
    depends_on:
      - message-broker
      - meetings-service
      - zima
