services:
  message-broker:
    image: rabbitmq:3-management-alpine
    container_name: message-broker
    ports:
      - 5672:5672 # for sender and consumer connections
      - 15672:15672 # for serve RabbitMQ GUI
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    labels:
      reproxy.port: 15672
      homepage.group: Zima
      homepage.name: Message broker

  zima-controller:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        SERVICE_PATH: packages/zima-controller
    container_name: zima
    ports:
      - ${PORT}:${PORT}
    expose:
      - ${PORT}
    environment:
      PORT: ${PORT}
      AMQP_SERVER_URL: ${AMQP_SERVER_URL}
      AMQP_FORMS_QUEUE_NAME: ${AMQP_FORMS_QUEUE_NAME}
      TELEGRAM_SERVICE_ADDRESS: ${TELEGRAM_SERVICE_ADDRESS}
      SMART_DEVICES_SERVICE_ADDRESS: ${SMART_DEVICES_SERVICE_ADDRESS}
    restart: unless-stopped
    depends_on:
      - message-broker
    labels:
      reproxy.server: "*"
      reproxy.route: "^/(.*)"
      reproxy.dest: "/$$1"
      homepage.group: Zima
      homepage.name: Zima Controller

  meetings-service:
    build:
      context: packages/meeting-service
      dockerfile: Dockerfile
    container_name: meetings-service
    volumes:
      - ./packages/meeting-service/credentials.json:/app/credentials.json
      - ./packages/meeting-service/token.json:/app/token.json
    environment:
      AMQP_MEETINGS_QUEUE_NAME: ${AMQP_MEETINGS_QUEUE_NAME}
      AMQP_SERVER_URL: ${AMQP_SERVER_URL}
    restart: unless-stopped
    depends_on:
      - message-broker
    labels:
      reproxy.enabled: 0
      homepage.group: Zima
      homepage.name: Meetings Service

  spotify-service:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        SERVICE_PATH: packages/spotify-service
    container_name: spotify-service
    hostname: spotify-service
    volumes:
      - ./packages/spotify-service/db/auth.json:/app/db/auth.json
    environment:
      HTTP_PORT: 3000
      AMQP_SERVER_URL: ${AMQP_SERVER_URL}
      AMQP_SPOTIFY_QUEUE_NAME: ${AMQP_SPOTIFY_QUEUE_NAME}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      SPOTIFY_REDIRECT_URI: ${SPOTIFY_REDIRECT_URI}
      AUTH_DB_PATH: /app/db/auth.json
    restart: unless-stopped
    depends_on:
      - message-broker
    expose:
      - 3000
    labels:
      homepage.group: Zima
      homepage.name: Spotify Service

  smart-devices-service:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        SERVICE_PATH: packages/smart-devices-service
    container_name: smart-devices-service
    hostname: smart-devices-service
    volumes:
      - ./packages/smart-devices-service/devices.json:/usr/src/app/packages/devices.json
      - persist-homekit:/usr/src/app/packages/smart-devices-service/persist
    environment:
      GRPC_ADDRESS: ${SMART_DEVICES_GRPC_ADDRESS}
      ERRORS_IS_CATCH_ENABLE: true
      ERRORS_NAME: smart-devices-service
      ERRORS_ENVIRONMENT: production
      ERRORS_DSN: ${ERRORS_DSN}
    expose:
      - 50051
    network_mode: host
    restart: unless-stopped
    labels:
      reproxy.enabled: 0
      homepage.group: Zima
      homepage.name: Smart Devices Service

  ansible-service:
    build:
      context: .
      dockerfile: packages/ansible-service/Dockerfile
      args:
        SERVICE_PATH: packages/ansible-service
        SSH_HOST: ${SSH_HOST}
        SSH_USER: ${SSH_USER}
        SSHPASS: ${SSH_PASS}
    container_name: ansible-service
    hostname: ansible-service
    volumes:
      - ./packages/ansible-service/ansible/playbooks:/usr/src/app/packages/ansible-service/ansible/playbooks
      - ${LOCAL_VPN_FILES_PATH}:${VPN_FILES_PATH}
    environment:
      AMQP_SERVER_URL: ${AMQP_SERVER_URL}
      AMQP_ANSIBLE_QUEUE_NAME: ${AMQP_ANSIBLE_QUEUE_NAME}
      PLAYBOOKS_DIR: ${PLAYBOOKS_DIR}
      VPN_FILES_PATH: ${VPN_FILES_PATH}
      SSH_USER: ${SSH_USER}
      SSH_HOST: ${SSH_HOST}
    restart: unless-stopped
    depends_on:
      - message-broker
    labels:
      reproxy.enabled: 0
      homepage.group: Zima
      homepage.name: Ansible Service

  forms-db:
    image: mongo:4.4-bionic
    container_name: forms-db
    restart: unless-stopped
    command: mongod --serviceExecutor adaptive
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DB}
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - formsdbdata:/data/db
    labels:
      reproxy.enabled: no
      homepage.group: Zima
      homepage.name: Forms DB

  forms-service:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        SERVICE_PATH: packages/forms-service
    container_name: forms-service
    hostname: forms-service
    environment:
      AMQP_SERVER_URL: ${AMQP_SERVER_URL}
      AMQP_ANSIBLE_QUEUE_NAME: ${AMQP_ANSIBLE_QUEUE_NAME}
      AMQP_MEETINGS_QUEUE_NAME: ${AMQP_MEETINGS_QUEUE_NAME}
      AMQP_SMART_DEVICES_QUEUE_NAME: ${AMQP_SMART_DEVICES_QUEUE_NAME}
      AMQP_SPOTIFY_QUEUE_NAME: ${AMQP_SPOTIFY_QUEUE_NAME}
      AMQP_FORMS_QUEUE_NAME: ${AMQP_FORMS_QUEUE_NAME}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB: ${MONGO_DB}
    restart: unless-stopped
    depends_on:
      - message-broker
      - forms-db
    labels:
      reproxy.enabled: no
      homepage.group: Zima
      homepage.name: Forms Service

  telegram-service:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        SERVICE_PATH: packages/telegram-service
    container_name: telegram-service
    hostname: telegram-service
    environment:
      GRPC_ADDRESS: ${TELEGRAM_GRPC_ADDRESS}
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_AUTH_PASSWORD: ${TELEGRAM_AUTH_PASSWORD}
      TELEGRAM_SESSION_STRING: ${TELEGRAM_SESSION_STRING}
      TELEGRAM_AUTH_PHONE_CODE: ${TELEGRAM_AUTH_PHONE_CODE}
      TELEGRAM_AUTH_PHONE_NUMBER: ${TELEGRAM_AUTH_PHONE_NUMBER}
    expose:
      - 50051
    restart: unless-stopped
    depends_on:
      - zima-controller
    labels:
      reproxy.enabled: no
      homepage.group: Zima
      homepage.name: Telegram Service


  reproxy:
    image: umputun/reproxy:master
    container_name: zima-api
    hostname: reproxy
    ports:
      - "18080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Europe/Warsaw
      - LISTEN=0.0.0.0:8080
      - DOCKER_ENABLED=true
      - DOCKER_AUTO=true
      - DEBUG=true
      - TIMEOUT_RESP_HEADER=640s
      - TIMEOUT_WRITE=640s
      - TIMEOUT_IDLE=640s
      - TIMEOUT_DIAL=640s
      - TIMEOUT_KEEP_ALIVE=640s
      - MAX_SIZE=0
      - MGMT_ENABLED=true
    restart: unless-stopped
    depends_on:
      - message-broker
      - meetings-service
      - zima-controller
    labels:
      homepage.group: Zima
      homepage.name: Zima API

  prometheus:
    image: prom/prometheus:v2.41.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3100:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  formsdbdata:
  persist-homekit:
  grafana-storage:
  prometheus-data:
