- hosts: all
  tasks:
    - name: "Execute ATV command"
      command: atvremote --id {{ lookup('env','ATV_ID') }} --companion-credentials {{ lookup('env','ATV_COMPANION_CREDENTIALS') }} {{ command }}
