---
- hosts: all
  tasks:
    - name: "Check if VPN already on"
      shell: "netstat -i | grep tun0"
      register: interfaces
      ignore_errors: true

    - name: "Save docker iptables rules into file"
      shell: "sudo iptables-save > ~/docker.rules"
      when: interfaces.stdout == ""

    - name: "Start forward rules"
      command: "sudo netfilter-persistent start"
      when: interfaces.stdout == ""

    - name: "Apply docker iptables rules"
      shell: "sudo iptables-restore -n ~/docker.rules"
      when: interfaces.stdout == ""

    - name: "Start OpenVPN"
      command: "sudo openvpn ~/ovpn/{{ vpn_name }}.ovpn"
      async: 1
      poll: 0
      when: interfaces.stdout == ""
